apiVersion: agentcore.amazon.com/v1
kind: Agent
metadata:
  name: ai-honeypot-detection-agent
  namespace: ai-honeypot-system
  labels:
    app: ai-honeypot
    component: detection
    version: v1.0.0
spec:
  description: "AI-Powered Honeypot System - Threat Detection Agent"
  runtime:
    type: python
    version: "3.11"
    entrypoint: "main:app"
    framework: "strands-agents"
    healthCheck:
      enabled: true
      path: "/health"
      intervalSeconds: 30
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo 'Graceful shutdown initiated'"]
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'Agent started successfully'"]
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  scaling:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  
  environment:
    - name: AWS_REGION
      value: "us-east-1"
    - name: LOG_LEVEL
      value: "INFO"
    - name: USE_MOCK_AI
      value: "false"
    - name: BEDROCK_MODEL_ID
      value: "anthropic.claude-3-haiku-20240307-v1:0"
    - name: DETECTION_CONFIDENCE_THRESHOLD
      value: "0.75"
    - name: MITRE_ATTACK_MAPPING
      value: "true"
    - name: AGENTCORE_RUNTIME_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: agentcore-config
          key: runtime-endpoint
  
  dependencies:
    - strands-agents>=0.1.0
    - bedrock-agentcore>=0.1.0
    - boto3>=1.34.0
    - fastapi>=0.104.0
    - pydantic>=2.5.0
    - httpx>=0.25.0
    - anthropic>=0.25.0
    - prometheus-client>=0.19.0
  
  interfaces:
    input:
      - name: threat_data
        type: json
        schema:
          type: object
          properties:
            source_ip:
              type: string
              description: "Source IP address of the threat"
            destination_ip:
              type: string
              description: "Destination IP address"
            threat_type:
              type: string
              description: "Type of threat detected"
            confidence:
              type: number
              minimum: 0
              maximum: 1
              description: "Confidence score of the threat"
            indicators:
              type: array
              items:
                type: string
              description: "List of threat indicators"
            timestamp:
              type: string
              format: date-time
              description: "Timestamp of the threat detection"
    
    output:
      - name: engagement_decision
        type: json
        schema:
          type: object
          properties:
            decision:
              type: string
              enum: ["ENGAGE", "MONITOR", "IGNORE"]
              description: "Engagement decision"
            confidence:
              type: number
              minimum: 0
              maximum: 1
              description: "Confidence in the decision"
            reasoning:
              type: string
              description: "AI-generated reasoning for the decision"
            mitre_techniques:
              type: array
              items:
                type: string
              description: "MITRE ATT&CK technique IDs"
            recommended_honeypots:
              type: array
              items:
                type: string
              description: "Recommended honeypot types for engagement"
            threat_assessment:
              type: object
              properties:
                severity:
                  type: string
                  enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
                attack_vector:
                  type: string
                potential_impact:
                  type: string
  
  communication:
    protocols:
      - http
      - agentcore-messaging
    
    endpoints:
      - name: evaluate_threat
        method: POST
        path: /evaluate
        description: "Evaluate threat data and make engagement decision"
      - name: health_check
        method: GET
        path: /health
        description: "Agent health check endpoint"
      - name: metrics
        method: GET
        path: /metrics
        description: "Prometheus metrics endpoint"
      - name: reputation_check
        method: POST
        path: /reputation
        description: "Check IP reputation"
      - name: ioc_extraction
        method: POST
        path: /iocs
        description: "Extract IOCs from text data"
  
  messaging:
    subscriptions:
      - topic: "threat.detected"
        handler: "process_threat_detection"
      - topic: "system.health_check"
        handler: "handle_health_check"
    
    publications:
      - topic: "engagement.decision"
        schema: "engagement_decision"
      - topic: "threat.analysis"
        schema: "threat_assessment"
  
  monitoring:
    healthCheck:
      path: /health
      intervalSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    
    readinessProbe:
      path: /health
      initialDelaySeconds: 10
      periodSeconds: 5
    
    metrics:
      - name: threats_evaluated_total
        type: counter
        description: "Total number of threats evaluated"
        labels: ["threat_type", "decision"]
      - name: engagement_decisions_total
        type: counter
        description: "Total number of engagement decisions made"
        labels: ["decision_type"]
      - name: detection_latency_seconds
        type: histogram
        description: "Time taken to evaluate threats"
        buckets: [0.1, 0.5, 1.0, 2.0, 5.0]
      - name: ai_processing_time_seconds
        type: histogram
        description: "Time taken for AI processing"
        buckets: [0.5, 1.0, 2.0, 5.0, 10.0]
      - name: threat_confidence_score
        type: histogram
        description: "Distribution of threat confidence scores"
        buckets: [0.1, 0.3, 0.5, 0.7, 0.9, 1.0]
  
  security:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  persistence:
    volumes:
      - name: logs
        mountPath: /app/logs
        size: 1Gi
        storageClass: gp3